CREATE TABLE Products(
	id BIGINT PRIMARY KEY IDENTITY,
	name NCHAR(30) UNIQUE NOT NULL,
	type NCHAR(14) NOT NULL,
	ingredients NCHAR(50) NOT NULL
)

ALTER TABLE Goods ADD productId BIGINT REFERENCES Products(id)